//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=localhost;uid=root;pwd=;database=stalk;charset=utf8;")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<RSAKeyValue><Modulus>7JOWqJNpEXahEQj5riBSplfIdREnO7kZQlBIo2aEXEdSk/lsu1Q2BfrJMT6" +
            "/E7T4sPYE+jh72zkVsP75DhwSanfZHy1lnRk0LDC/KG1wVmWYUyRXCZB1hKhWKrwqFNWiXKysPNuhB1C" +
            "zpSd1u66H26cSEu5g7vdeLHcKawTrZu3+IHF4vutOeivc0ibO4+Q9p9Q6oseWOfJ6xJkm3RdwaeOU0Gw" +
            "VH5H1NBbZuvQyPErrQYTb9l/gVSsASt4UEyE1sVtPeZTuwAI3nkdq6PJAmKnHsV2Zl2bsbGLK5tPpk6Y" +
            "IdKxJ5chWgNq/4m+n0Hq9iHY0Ofxuz66v8gWd9cRziw==</Modulus><Exponent>AQAB</Exponent>" +
            "<P>+Jrnju3L35OtUlcAtyfQ4wU9Stt1yA/8t+tCjaAOCjUkDDucgBpw0JguGV4mT880vJ/lO6zZQHfPO" +
            "0NnhtewO4wa77co8/t742N0uqRAoeGfs2mLwAFzBwDnW77/YmlgOF+doYjaqbrsJlqvU0A8i0HIDDp8g" +
            "Uh1ZHUqpJI4osE=</P><Q>850WglkLUFqhQrGFddLIBYLq7AKgrxMGPI1iApqQpuBJoG01/Qpjw0ZQk+" +
            "+o7gBhuiY+lKtjd8mLHi2GMOtRamKLJPqa4EgkN0ehonWgPU7nlZWdU4uVeAuYTZmH7/mBrEHI5DEI7I" +
            "ylxNBAKoFjg8/FHKJfdO1UrZwjzha/BUs=</Q><DP>wbQw6HTwfWwbiCSyMgOcBsd2UnVc+F08lDGC0c" +
            "b8KYfuZnmsH0R60o1AnhN11omklbQgcLblMA4qMgr7B13Xuw4XjuAv0KsKhMphkWuZ0Ih0Xt7GPPzkG3" +
            "jgy+OuKYfhqQsXT13KwqUai2ftY/iRNBA1RxHrIPDMR1HjwAcOigE=</DP><DQ>n31msSvOxmqvTNSgB" +
            "YVbwo/1cVI/FJ+l45rEYeQDc90/FrKpN+LHcZ7lPhUXScoiMRa8veR/GHtwgu9W/UvyX23onusa3l8cp" +
            "rxUy+GqaLjx0PLEr1+hGZitu5AaeTemd7oR5aNcrlFebb3RZIKVPkSWTarYR9rhJ1Aj+NbXdIU=</DQ>" +
            "<InverseQ>MdAeUSfKj/2+LlxK1XXR5mK+ukxGToz3bQTaQYzGEZ2uFTGZJQDMGb1785T8qAKRBOLsPt" +
            "9pA4V1aA0HPwtO7ipceeyDr93or0TiYOnoQBRbJOvA65Ox3udqQ9htj9Xr/U+4xeEnRQ76OfjDZdHef6" +
            "ATu/UTC+YI5T9xXHiXA/U=</InverseQ><D>N9GO35GAXd12nVVXy+zWc2cM5go5Do9a1Vmp+dvLaRZu" +
            "9nkIXZ697GVCqTrbzKOLdf1mKT/AgXYTlyJh0yFueu5yLTgB3LJArBiIUdqYgdoQubU+UARkpfst8YFa" +
            "EHZji6g2L1nGwboZ2OLZlYHVjk76JbtW5as57hXcQGn1vOAATa9E/4EHwApi0MD00t2yZPmqHfOImVnE" +
            "fxFjpUwGIMB9GTLVOBUM7Swtd0cb4LYnMaExI4u5/griA1QCA+meettV1iWRMT3ZBMxTLMM2D2LsL9HS" +
            "uomTFue5WCDcH2Z36XZxlcWwURPNFMrJoZ2ZQncz9jIeInldgtLVBZbggQ==</D></RSAKeyValue>")]
        public string PrivateKey {
            get {
                return ((string)(this["PrivateKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("443")]
        public int ServerPort {
            get {
                return ((int)(this["ServerPort"]));
            }
        }
    }
}
